Pass validation
$ make validate
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Colors.mk ../tools/Makefiles/Helpers.mk
--
[*] Running validators
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
Validator HelpValidator failed!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/icon_validator/validate.py", line 29, in validate
    v.validate(spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/icon_validator/rules/help_validator.py", line 99, in validate
    HelpValidator.validate_title_spelling(spec.spec_dictionary(), spec.raw_help())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/icon_validator/rules/help_validator.py", line 63, in validate_title_spelling
    raise Exception('Help section contains non-matching title in line: {}'.format(line))
Exception: Help section contains non-matching title in line: * 1.0.3 - Update to use the `komand/python-3-37-slim-plugin:3` Docker image | Changed description in dirname action output | Changed `Exception` to `PluginException` | Changed bare strings in params.get and output to static fields from schema